name: Label Pull Requests

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      environment:
      name: CAT
      #url: 'http://...  '
      description: 'Ready for Release to Production'
      required: true
      default: 'Re-run Action'
      type: choice
      options:
          - Re-run Action  

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add default label
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.EMAIL_USERNAME }} #${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        label: "default-label"
        body: 
          A new Pull Request has been opened in the repository:
          Repository: ${{ github.repository }}
          Pull Request Title: ${{ github.event.pull_request.title }}
          Pull Request Body: ${{ github.event.pull_request.body }}
          Issue URL: ${{ github.event.pull_request.html_url }}
        to: derick.williams1@nara.gov
        from: ${{ secrets.EMAIL_USERNAME }}
        secure: true
        priority: High
