name: Send Email on Pull Request

on:
  pull_request:
    types: [opened]

  workflow_dispatch:
    inputs:
      run_reason:
       description: 'Add button to manually Re-run the Action'
       required: true
       default: Re-run Action
       type: choice
       options:
          - Re-run Action

jobs:
  send_email:
    runs-on: ubuntu-latest

    strategy:
      matrix:
         node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Email Credentials
      run: |
        #echo "email_username=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
        echo "email_password=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV  
        echo ${{ secrets.EMAIL_USERNAME }} | sed 's/./& /g'
    - name: Send email
      uses: action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'New Pull Request Opened: ${{ github.event.pull_request.title }}'
        body: |
          A new Pull Request has been opened in the repository:
          Repository: ${{ github.repository }}
          Issue Title: ${{ github.event.pull_request.title }}
          Issue Body: ${{ github.event.pull_request.body }}
          Issue URL: ${{ github.event.pull_request.html_url }}
        to: ${{ secrets.EMAIL_USERNAME }}
        from: ${{ secrets.EMAIL_PASSWORD }}
        secure: true
        priority: low
