name: Update Version and Create Release PR Workflow

  on:
	workflow_dispatch:
	    inputs:
	    version:
		    description: 'Version name'
		    required: true
		    default: 'Major'
		    type: choice
		    options:
		      - Major
		      - Minor
		      - Patch
	              - Full Build
	              - Partial Build

  jobs:
	version:
	    runs-on: ubuntu-latest

            strategy:
              matrix:
               node-version: [22.2.0]
	       
	    steps:
	      - name: Checkout code
	        uses: actions/checkout@v3
	 
	      - name: Setup Node.js
	        uses: actions/setup-node@v3
	        with:
	          node-version: '22.x'
	   
	      - name: Install dependencies
	        run: npm install
		  - name: Set up Git
		    run: |
	          git config user.name "ddwilliams1"
	          git config user.email "derick.williams1@nara.gov"

              - name: Set environment variables
                run: echo "NODE_ENV=production" >> $GITHUB_ENV

              - name: Display directory structure
                run: ls -la /home/runner/work/*

              - name: Set up Email Credentials
	        run: |
	        echo "email_username=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
	        echo "email_password=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
	   
	      - name: Update the version
	        id: update_version
	        run: |
	          echo "version=$(npm version ${{ github.event.inputs.version }} --no-git-tag-version)" >> $GITHUB_OUTPUT
	      
              - name: Update Changelog
		    id: update_changelog
	        run: |
	          sed -i 's/Unreleased/${{ steps.update_version.outputs.version }}/g'   CHANGELOG.md
	   
	      - name: Create pull request
	        id: create_pr
	        uses: peter-evans/create-pull-request@v5
	        with:
	          token: ${{ secrets.EMAIL_USERNAME }} #${{ secrets.GITHUB_TOKEN }}
	          branch: release/${{ steps.update_version.outputs.version }}
	          title: "Release: ${{ steps.update_version.outputs.version }} Pull Request"
	          body: "This pull request contains the updated package.json with the new release version"
	          base: main
