# Name of the workflow
name: Ziz Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"  

  workflow_dispatch:
    inputs:
      environment:
        description: 'Re-Run Action'
        required: true
        default: 'Re-run Action'
        type: choice
        options:
          - Re-Run Action    

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

      - name: Set up Email Credentials
        run: |
          #echo "email_username=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "email_password=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV  
          echo ${{ secrets.EMAIL_USERNAME }} | sed 's/./& /g'          

      - name: Send email notification on release
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'CM: NARA Project Release Ready for Ops Deploy - PROD'
          body: 'A NARA Project Release is ready for Ops Deployment to PROD environment: ${{ steps.create_release.outputs.html_url }}'
          to: ${{ secrets.EMAIL_USERNAME }}, #janice.cobb@nara.gov, #seema.dheman@nara.gov, #Sherli.Nambiar@nara.gov #Chandni.Bedi@nara.gov
          from: ${{ secrets.EMAIL_USERNAME }}, #janice.cobb@nara.gov, #seema.dheman@nara.gov
